sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t braven36/docker-react
script:
  - docker run -e CI=true braven36/docker-react npm run test -- --coverage