sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t braven36/docker-react
script:
  - docker run -e CI=true braven36/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: elasticbeanstalk-us-west-2-294028414347
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY